### PR TITLE
Change 'app:create' to 'app:install'

### LINKED ISSUE #87: Rename `app:create` cli command to `app:install`
As a dApp developer, I expected `app:create` to scaffold a directory with skeleton dApp so I could start a new project, similar to create-react-app. Perhaps we should reserve "create" for the "create-react-app"-like experience, and use "install" instead.

### PR DESCRIPTION
**Pull request by canadaduane**
Make it clearer to the CLI user that an existing app is expected as input to the command.

Fixes #87

### CODE REVIEW

**Comment by PaulLeCam** [comment]
I agree with Adam `install` is confusing here, especially since it's a command we might want to provide at some point to install an existing app directly from the CLI.

**Comment by canadaduane** [comment]
But this doesn't create a new app. I called "run app:create", supplying a non-existent directory, and nothing was created.

"Install" seems as close to what it does as I know--it takes an existing (already created app) and "installs" it into the vault.

**Comment by avclarke** [comment]
It’s really about creating a new instance of an app in the vault, as a developer you’re creating the record, generating an app ID, setting name, version and in the future description, app icon etc. As for linking to the contents of the app, right now you are only able to link to a existing contents but in future you’ll be able to create a new template app like you were expecting,  generated from a bootstrap script and already be configured to work with SDK, Morpheus UI etc.

**Comment by canadaduane** [comment]
So the intent is to create an app in the future?

I feel like this still conflates two separate things, even if in the future it creates an app (i.e. its contents) for you. Suppose we make "app:create" do all the things you've outlined, what should a cli-user call if they've used `create-react-app` or some other external tool to supply the contents and want to add it to the vault?

What I'd like to see is a set of simple commands that are called by a higher-level command. For example, suppose we have some simple commands, "app:generate" and "app:link", and these get called by a higher-level command "app:create".

As it stands, I still think "app:create" sets expectations that are unmet until it does the contents-creation part.

**Comment by avclarke** [comment]
I'm not sure app:link works either, as I mentioned above it's really about a developer creating an app in the daemon and generating an app ID. It's also consistent with the underlying daemon api if you look at the code, so I think it could be bit misleading for a developer following the underlying code and seeing methods around app creation and then at the edge it's called app:link.

I feel it's similar if you went to iTunes or Google play to deploy your app, you'd first create a new app, which would generate an app ID, and then upload the contents. Maybe the linking contents part is a bit confusing but it was mainly to streamline the process to a single step.

**Comment by canadaduane** [comment]
I think I'm going to throw in the towel at this point. Please consider that as a new user of the cli "this was confusing to me." Perhaps other developers' feedback (if given) can shed more light.

**Pull request closed without merging**
